### ISSUE TITLE
[get_chart_data] SQL request error with multiple City locations as filter

### ISSUE THREAD

**Issue by andrejadd** [andrejadd/AirExplorer#27]
127.0.0.1 - - [12/Aug/2018 23:51:14] "GET /charts/get_chart_data?source=aqerep&pollutants=5&locations=AMSDORF%3ACity%2CALTENBURG%3ACity%2CAALEN%3ACity%2CAACHEN%3ACity&aggregation=year&groupby=None&primary_attribute=Time HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrej/Schreibtisch/2_Airquality/3_DevFiles/AirExplorer/server/airserver.py", line 69, in get_chart_data
    request.args.get('primary_attribute'))))
  File "/home/andrej/Schreibtisch/2_Airquality/3_DevFiles/AirExplorer/server/scripts/DataConnector.py", line 282, in get_chart_data
    tbl = self.airDB.execute_sql(sql, True)
  File "/home/andrej/Schreibtisch/2_Airquality/3_DevFiles/AirExplorer/server/scripts/AirDB.py", line 129, in execute_sql
    cur.execute(sqlCmd)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \') OR b.Col_2="AALEN") OR b.Col_2="AACHEN") GROUP BY pa ORDER BY pa ASC\' at line 1')
^[[B

**Comment by andrejadd** [comment]
parenthesis was set wrong in SQL query, fixed
